name: CI of mc_panda_lirmm

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run on Sunday, Tuesday and Thursday nights
    - cron: '0 23 * * 0,1,4'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install ROS dependencies
      if: matrix.os == 'ubuntu-20.04'
      run: |
        set -x
        set -e
        export ROS_DISTRO="noetic"
        sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
        sudo apt-get update -qq
        sudo apt-get -qq remove libomp5-9 || true
        sudo apt-get install -qq ros-${ROS_DISTRO}-libfranka ros-${ROS_DISTRO}-franka-ros
        . /opt/ros/${ROS_DISTRO}/setup.bash
        echo "ROS_DISTRO=${ROS_DISTRO}" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> $GITHUB_ENV
        echo "ROS_MASTER_URI=${ROS_MASTER_URI}" >> $GITHUB_ENV
        echo "ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}" >> $GITHUB_ENV
        echo "PYTHONPATH=${PYTHONPATH}" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}" >> $GITHUB_ENV
        echo "PATH=${PATH}" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV
    - name: Install mc_rtc
      run: |
        set -x
        set -e
        curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/head/setup.deb.sh' | sudo -E bash
        sudo apt-get install -qq libmc-rtc-dev mc-rtc-utils python3-mc-rtc ros-${ROS_DISTRO}-mc-rtc-plugin mc-panda
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: gcc
        build-type: RelWithDebInfo
    - name: Slack Notification
      if: failure()
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: '#ci'
        slack-text: >
          [mc_panda] Build *${{ matrix.os }}/${{ matrix.build-type }}* failed on ${{ github.ref }}
